name: resnet50
inputs:
  - name: image
    dtype_str: float32
    shapes:
      dims_names: [batch_size, channels, height, width]
      example: [224, 224, 3]
      runtime: [1, 3, -1, -1]
      optimization:
        min: [1, 3, 128, 128]
        opt: [1, 3, 256, 256]
        max: [1, 3, 512, 512]
outputs:
  - name: probs
    shape:
      runtime: [1, 1000]
      dims_names: [batch_size, probs]
