inputs:
- dtype_str: float32
  name: image
  shapes:
    dims_names:
    - batch_size
    - channels
    - height
    - width
    example: !!python/tuple
    - 224
    - 224
    - 3
    optimization:
      max:
      - 1
      - 3
      - 512
      - 512
      min:
      - 1
      - 3
      - 128
      - 128
      opt:
      - 1
      - 3
      - 256
      - 256
    runtime:
    - 1
    - 3
    - -1
    - -1
name: resnet50
outputs:
- name: probs
  shape:
    dims_names:
    - batch_size
    - probs
    runtime:
    - 1
    - 1000
